### ISSUE TITLE
Device Installer fails for xcku025-ffva1156-1-c

### ISSUE THREAD

**Issue by DallonTG** [byuccl/RapidSmith2#279]
Running the device installer on a generated XDLRC for xcku025-ffva1156-1-c fails with a Null Pointer Exception.

Here is the trace:
```
Parsing Device Info file

Exception in thread "main" java.lang.NullPointerException
	at edu.byu.ece.rapidSmith.device.Device.constructSiteExternalConnections(Device.java:653)
	at edu.byu.ece.rapidSmith.device.Device.constructDependentResources(Device.java:616)
	at edu.byu.ece.rapidSmith.device.creation.DeviceGenerator.generate(DeviceGenerator.java:165)
	at edu.byu.ece.rapidSmith.device.creation.DeviceFilesCreator.createDevice(DeviceFilesCreator.java:59)
	at edu.byu.ece.rapidSmith.util.Installer.main(Installer.java:105)
```

No errors occurred while the xdlrc was generated and the generated device info file from Tincr is identical to previous device info files for the part. So I'm inclined to believe it isn't a problem with Tincr.

**Comment by DallonTG** [comment]
A little more info: I've determined that the error is occurring (a null site template is being returned) when getSiteTemplate(siteType) is called, when the site type is GND.

**Comment by DallonTG** [comment]
I have determined this to be a Tincr error and will be submitting a PR for it in the Tincr repo.
